name: Hello World
  on:
    push:
      branches: ["main"]
    pull_request:
      branches: ["main"]
    workflow_dispatch:
    
  jobs:
    hello:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        - name: Says Hello
        run : echo Hello World
  jobs:
    bye:
      runs-on: ubuntu-latest
      steps:
      - name: Says Bye
        run : echo Bye
      need: [hello]
      
    
      





