# This is a basic workflow to help you get started with Actions

name: Print Issue Detais

on:
  issues:
    types:
      - opened
  workflow_dispatch:

jobs:
  print:
    runs-on: ubuntu-latest
    steps:
      - name: Printing content of Issues
        run: 
         echo  "${{ github.event.issue.title }}"
         echo  "${{ github.event.issue.body }}"
      


  
